services:
  discovery:
    build: discovery-service
    ports:
      - "8081:8081"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  user:
    build: user-service
    depends_on:
      - discovery
    ports:
      - "8082:8082"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  product:
    build: user-service
    depends_on:
      - user
    ports:
      - "8083:8083"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  order:
    build: user-service
    depends_on:
      - inventory
    ports:
      - "8084:8084"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  inventory:
    build: user-service
    depends_on:
      - product
    ports:
      - "8085:8085"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  gateway:
    build: api-gateway
    depends_on:
      - order
    ports:
      - "8080:8080"
    network_mode: bridge
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"